insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132001','White','#FFFFFF');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132002','Black','#000000	');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132003','Red','#FF0000');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132004','Blue','#0000FF');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132005','Yellow','#FFFF00');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132006','Green','#008000');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132007','Orange','#FFA500');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132008','Gold','#FFD700');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132009','Silver','#C0C0C0');
insert into `smartphonedb`.`color` (`colorId`,`colorName`,`colorCode`) values ('132010','Gray','#808080');
