-- MySQL Script generated by MySQL Workbench
-- Wed May  5 11:36:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartphonedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartphonedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartphonedb` DEFAULT CHARACTER SET utf8 ;
USE `smartphonedb` ;

-- -----------------------------------------------------
-- Table `smartphonedb`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartphonedb`.`Brand` ;

CREATE TABLE IF NOT EXISTS `smartphonedb`.`Brand` (
  `brandId` INT NOT NULL,
  `brandName` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`brandId`),
  UNIQUE INDEX `brandname_UNIQUE` (`brandName` ASC) VISIBLE,
  UNIQUE INDEX `brandid_UNIQUE` (`brandId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartphonedb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartphonedb`.`Product` ;

CREATE TABLE IF NOT EXISTS `smartphonedb`.`Product` (
  `productId` INT NOT NULL,
  `productName` VARCHAR(80) NOT NULL,
  `productDescription` VARCHAR(255) NULL DEFAULT NULL,
  `price` INT NOT NULL,
  `manufactureDate` DATETIME NULL,
  `brand_brandId` INT NOT NULL,
  PRIMARY KEY (`productId`),
  UNIQUE INDEX `productname_UNIQUE` (`productName` ASC) VISIBLE,
  INDEX `fk_product_brand_idx` (`brand_brandId` ASC) VISIBLE,
  CONSTRAINT `fk_product_brand`
    FOREIGN KEY (`brand_brandId`)
    REFERENCES `smartphonedb`.`Brand` (`brandId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartphonedb`.`Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartphonedb`.`Color` ;

CREATE TABLE IF NOT EXISTS `smartphonedb`.`Color` (
  `colorId` INT NOT NULL,
  `colorName` VARCHAR(45) NOT NULL,
  `colorCode` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`colorId`),
  UNIQUE INDEX `colorcode_UNIQUE` (`colorCode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartphonedb`.`ProductColor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartphonedb`.`ProductColor` ;

CREATE TABLE IF NOT EXISTS `smartphonedb`.`ProductColor` (
  `productId` INT NOT NULL,
  `colorId` INT NOT NULL,
  INDEX `fk_product_color1_idx` (`colorId` ASC) VISIBLE,
  INDEX `fk_product_color_product_idx` (`productId` ASC) VISIBLE,
  PRIMARY KEY (`productId`, `colorId`),
  CONSTRAINT `fk_product_color_color`
    FOREIGN KEY (`colorId`)
    REFERENCES `smartphonedb`.`Color` (`colorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_color_product`
    FOREIGN KEY (`productId`)
    REFERENCES `smartphonedb`.`Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
